ci: Test with different version of Git (#402)
If we're going to add support for things like git-replay,
we'll end up needing to test against different versions of Git.
Set this up so that we can also establish a minimum required version.

Minimum required Git is currently 2.38 because:

- 2.31 added `GIT_CONFIG_KEY_<N>` support
- 2.38 added `git merge-tree` command

We use both features for the integration tests.
git-spice itself could probably go lower,
but if we can't test for it, it's not supported so this will have to do.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -37,16 +37,64 @@ jobs:
 
   test:
     runs-on: ${{ matrix.os }}
-    name: Test (${{ matrix.os}})
+    name: Test (${{ matrix.os}}, Git ${{ matrix.git-version }})
+
     strategy:
       matrix:
         os: ["ubuntu-latest", "windows-latest"]
+        git-version: ["system"]
+        include:
+          # On Linux, also test against specific versions built from source.
+          - {os: ubuntu-latest, git-version: "2.38.0"}
+
     steps:
     - uses: actions/checkout@v4
     - name: Set up Go
       uses: actions/setup-go@v5
       with:
         go-version: ${{ env.GO_VERSION }}
+
+    # TODO: extract into separate action
+    - name: Determine Git cache directory
+      shell: bash
+      if: matrix.git-version != 'system'
+      run: |
+        echo "GIT_VERSION=$GIT_VERSION" >> "$GITHUB_ENV"
+        echo "GIT_CACHE_DIR=$HOME/.cache/git/$GIT_VERSION" >> "$GITHUB_ENV"
+      env:
+        GIT_VERSION: ${{ matrix.git-version }}
+    - name: Fill Git cache
+      if: matrix.git-version != 'system'
+      uses: actions/cache@v4
+      with:
+        path: ${{ env.GIT_CACHE_DIR }}
+        key: ${{ runner.os }}-git-${{ matrix.git-version }}
+    - name: Install Git
+      shell: bash
+      if: matrix.git-version != 'system'
+      run: |
+        if [[ ! -x "$GIT_CACHE_DIR/bin/git" ]]; then
+          URL=https://mirrors.edge.kernel.org/pub/software/scm/git/git-${GIT_VERSION}.tar.gz
+          echo "Downloading Git $GIT_VERSION from $URL"
+          sudo apt-get install \
+              dh-autoreconf libcurl4-gnutls-dev libexpat1-dev gettext \
+              libz-dev libssl-dev
+          GIT_SRC_DIR=$(mktemp -d)
+          ( mkdir -p "$GIT_SRC_DIR" &&
+            cd "$GIT_SRC_DIR" &&
+            (curl -sSL "$URL" | tar -xz --strip-components=1) &&
+            make prefix="$GIT_CACHE_DIR" &&
+            make prefix="$GIT_CACHE_DIR" install )
+        fi
+        if [[ ! -x "$GIT_CACHE_DIR/bin/git" ]]; then
+          echo "Failed to build Git $GIT_VERSION"
+          exit 1
+        fi
+        echo "$GIT_CACHE_DIR/bin" >> "$GITHUB_PATH"
+    - name: Report Git version
+      shell: bash
+      run:
+        git --version
 
     - name: Test
       run: make cover
